spring:
  datasource:
    url: jdbc:postgresql://${HOST}:5432/
#    url: jdbc:postgresql://localhost:5432/clevertec-gift-certificate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/postgresql

